CREATE TABLE "admin_assist_projection_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_assist_projection_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"global_assist_multiplier" numeric(4, 2) DEFAULT '1.0',
	"creativity_boost" numeric(4, 2) DEFAULT '1.15',
	"low_creativity_threshold" numeric(4, 2) DEFAULT '0.65',
	"elite_attack_multiplier" numeric(4, 2) DEFAULT '1.35',
	"strong_attack_multiplier" numeric(4, 2) DEFAULT '1.15',
	"average_attack_multiplier" numeric(4, 2) DEFAULT '1.00',
	"weak_attack_multiplier" numeric(4, 2) DEFAULT '0.85',
	"promoted_attack_multiplier" numeric(4, 2) DEFAULT '0.75',
	"min_assists_per_game" numeric(4, 2) DEFAULT '0.3',
	"max_assists_per_game" numeric(4, 2) DEFAULT '2.5',
	"last_updated" timestamp DEFAULT now(),
	"updated_by" varchar DEFAULT 'admin'
);
--> statement-breakpoint
CREATE TABLE "admin_cs_projection_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_cs_projection_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"decay_factor" numeric(4, 3) DEFAULT '0.02',
	"weak_defense_boost" numeric(4, 2) DEFAULT '3.0',
	"average_defense_boost" numeric(4, 2) DEFAULT '1.75',
	"strong_defense_boost" numeric(4, 2) DEFAULT '1.3',
	"elite_defensive_floor" numeric(4, 1) DEFAULT '25',
	"strong_defensive_floor" numeric(4, 1) DEFAULT '22',
	"average_defensive_floor" numeric(4, 1) DEFAULT '18',
	"weak_defensive_floor" numeric(4, 1) DEFAULT '16',
	"promoted_defensive_floor" numeric(4, 1) DEFAULT '15',
	"derby_cs_multiplier" numeric(4, 2) DEFAULT '0.82',
	"top_six_cs_multiplier" numeric(4, 2) DEFAULT '0.88',
	"relegation_battle_cs_multiplier" numeric(4, 2) DEFAULT '0.78',
	"early_kickoff_cs_multiplier" numeric(4, 2) DEFAULT '1.06',
	"late_kickoff_cs_multiplier" numeric(4, 2) DEFAULT '0.93',
	"post_european_cs_multiplier" numeric(4, 2) DEFAULT '0.87',
	"midweek_fixture_cs_multiplier" numeric(4, 2) DEFAULT '0.95',
	"season_finale_cs_multiplier" numeric(4, 2) DEFAULT '0.90',
	"new_manager_bounce_cs_multiplier" numeric(4, 2) DEFAULT '1.03',
	"weather_conditions_cs_multiplier" numeric(4, 2) DEFAULT '1.02',
	"last_updated" timestamp DEFAULT now(),
	"updated_by" varchar DEFAULT 'admin'
);
--> statement-breakpoint
CREATE TABLE "admin_goal_projection_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_goal_projection_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"global_tier_multiplier" numeric(4, 2) DEFAULT '1.25',
	"low_confidence_boost" numeric(4, 2) DEFAULT '1.25',
	"low_confidence_threshold" numeric(4, 2) DEFAULT '0.65',
	"derby_goals_multiplier" numeric(4, 2) DEFAULT '0.87',
	"top_six_goals_multiplier" numeric(4, 2) DEFAULT '1.12',
	"relegation_battle_goals_multiplier" numeric(4, 2) DEFAULT '0.83',
	"early_kickoff_goals_multiplier" numeric(4, 2) DEFAULT '0.94',
	"late_kickoff_goals_multiplier" numeric(4, 2) DEFAULT '1.07',
	"post_european_goals_multiplier" numeric(4, 2) DEFAULT '0.88',
	"midweek_fixture_goals_multiplier" numeric(4, 2) DEFAULT '0.91',
	"season_finale_goals_multiplier" numeric(4, 2) DEFAULT '1.05',
	"new_manager_bounce_goals_multiplier" numeric(4, 2) DEFAULT '1.08',
	"weather_conditions_goals_multiplier" numeric(4, 2) DEFAULT '0.96',
	"market_floor_multiplier" numeric(4, 2) DEFAULT '0.4',
	"market_ceiling_multiplier" numeric(4, 2) DEFAULT '2.0',
	"absolute_min_goals" numeric(4, 2) DEFAULT '0.3',
	"absolute_max_goals" numeric(4, 2) DEFAULT '4.2',
	"last_updated" timestamp DEFAULT now(),
	"updated_by" varchar DEFAULT 'admin'
);
--> statement-breakpoint
CREATE TABLE "admin_goals_against_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_goals_against_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"global_defensive_multiplier" numeric(4, 2) DEFAULT '1.0',
	"defensive_confidence_boost" numeric(4, 2) DEFAULT '0.85',
	"weak_defense_threshold" numeric(4, 2) DEFAULT '0.60',
	"elite_defense_multiplier" numeric(4, 2) DEFAULT '0.75',
	"strong_defense_multiplier" numeric(4, 2) DEFAULT '0.85',
	"average_defense_multiplier" numeric(4, 2) DEFAULT '1.0',
	"weak_defense_multiplier" numeric(4, 2) DEFAULT '1.15',
	"promoted_defense_multiplier" numeric(4, 2) DEFAULT '1.25',
	"min_goals_against" numeric(4, 2) DEFAULT '0.5',
	"max_goals_against" numeric(4, 2) DEFAULT '3.5',
	"last_updated" timestamp DEFAULT now(),
	"updated_by" varchar DEFAULT 'admin'
);
--> statement-breakpoint
CREATE TABLE "admin_match_projection_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_match_projection_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"home_advantage_multiplier" numeric(4, 2) DEFAULT '1.15',
	"strength_multiplier_base" numeric(4, 2) DEFAULT '2.2',
	"home_min_goals" numeric(4, 2) DEFAULT '0.5',
	"home_max_goals" numeric(4, 2) DEFAULT '4.0',
	"away_min_goals" numeric(4, 2) DEFAULT '0.3',
	"away_max_goals" numeric(4, 2) DEFAULT '3.5',
	"clean_sheet_exponent" numeric(4, 2) DEFAULT '1.0',
	"clean_sheet_multiplier" numeric(4, 2) DEFAULT '100',
	"derby_match_multiplier" numeric(4, 2) DEFAULT '0.92',
	"top_six_match_multiplier" numeric(4, 2) DEFAULT '1.08',
	"relegation_battle_multiplier" numeric(4, 2) DEFAULT '0.88',
	"last_updated" timestamp DEFAULT now(),
	"updated_by" varchar DEFAULT 'admin'
);
--> statement-breakpoint
CREATE TABLE "daily_player_prices" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"player_id" integer NOT NULL,
	"player_name" varchar NOT NULL,
	"record_date" date NOT NULL,
	"original_price" integer NOT NULL,
	"current_price" integer NOT NULL,
	"ownership" numeric(5, 2) NOT NULL,
	"total_transfers_in" integer NOT NULL,
	"total_transfers_out" integer NOT NULL,
	"daily_transfers_in" integer DEFAULT 0,
	"daily_transfers_out" integer DEFAULT 0,
	"price_change_event" integer DEFAULT 0,
	"team_id" integer,
	"position" varchar,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "fpl_content_creators" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fpl_content_creators_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"manager_id" integer NOT NULL,
	"manager_name" varchar(100) NOT NULL,
	"player_name" varchar(100),
	"description" text,
	"twitter_handle" varchar(100),
	"youtube_url" varchar(255),
	"followers" integer,
	"is_active" boolean DEFAULT true,
	"added_date" timestamp DEFAULT now(),
	"last_updated" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "fpl_creator_tracking" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fpl_creator_tracking_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"creator_id" integer NOT NULL,
	"gameweek" integer NOT NULL,
	"overall_rank" integer,
	"overall_points" integer,
	"gameweek_points" integer,
	"gameweek_rank" integer,
	"team_value" numeric(4, 1),
	"bank" numeric(4, 1),
	"total_transfers" integer,
	"free_transfers" integer,
	"wildcard_used" boolean DEFAULT false,
	"bench_boost_used" boolean DEFAULT false,
	"free_hit_used" boolean DEFAULT false,
	"triple_captain_used" boolean DEFAULT false,
	"captain_player_id" integer,
	"captain_player_name" varchar(100),
	"vice_captain_player_id" integer,
	"vice_captain_player_name" varchar(100),
	"transfers_in" json,
	"transfers_out" json,
	"hits_taken" integer DEFAULT 0,
	"recorded_at" timestamp DEFAULT now(),
	"is_verified" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "fpl_teams" (
	"id" integer PRIMARY KEY NOT NULL,
	"name" varchar NOT NULL,
	"short_name" varchar NOT NULL,
	"code" integer NOT NULL,
	"expected_goals_per_game" numeric(4, 2),
	"goal_variance" numeric(4, 2),
	"goal_confidence" numeric(4, 2),
	"base_clean_sheet_rate" numeric(4, 2),
	"home_bonus" numeric(4, 2),
	"clean_sheet_confidence" numeric(4, 2),
	"attacking_tier" varchar,
	"defensive_tier" varchar,
	"last_updated" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "gameweek_player_data" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"gameweek" integer NOT NULL,
	"season" text DEFAULT '2025/26' NOT NULL,
	"minutes" integer DEFAULT 0,
	"goals_scored" integer DEFAULT 0,
	"assists" integer DEFAULT 0,
	"clean_sheets" integer DEFAULT 0,
	"goals_conceded" integer DEFAULT 0,
	"own_goals" integer DEFAULT 0,
	"penalties_saved" integer DEFAULT 0,
	"penalties_missed" integer DEFAULT 0,
	"yellow_cards" integer DEFAULT 0,
	"red_cards" integer DEFAULT 0,
	"saves" integer DEFAULT 0,
	"bonus" integer DEFAULT 0,
	"bps" integer DEFAULT 0,
	"total_points" integer DEFAULT 0,
	"defensive_contribution" integer DEFAULT 0,
	"tackles" integer DEFAULT 0,
	"recoveries" integer DEFAULT 0,
	"clearances_blocks_interceptions" integer DEFAULT 0,
	"starts" integer DEFAULT 0,
	"was_home" boolean DEFAULT false,
	"opponent_team" integer,
	"fixture_id" integer,
	"kickoff_time" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "gameweek_update_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"gameweek" integer NOT NULL,
	"season" text DEFAULT '2025/26' NOT NULL,
	"update_type" text NOT NULL,
	"players_updated" integer DEFAULT 0,
	"errors" jsonb,
	"started_at" timestamp DEFAULT now(),
	"completed_at" timestamp,
	"duration_ms" integer
);
--> statement-breakpoint
CREATE TABLE "historical_player_stats" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"player_id" integer NOT NULL,
	"player_name" varchar NOT NULL,
	"season" varchar NOT NULL,
	"team_id" integer NOT NULL,
	"team_name" varchar NOT NULL,
	"position" varchar NOT NULL,
	"element_type" integer NOT NULL,
	"goals_scored" integer DEFAULT 0 NOT NULL,
	"assists" integer DEFAULT 0 NOT NULL,
	"clearances_blocks_interceptions" integer DEFAULT 0 NOT NULL,
	"tackles" integer DEFAULT 0 NOT NULL,
	"recoveries" integer DEFAULT 0 NOT NULL,
	"defensive_contribution" integer DEFAULT 0 NOT NULL,
	"clean_sheets" integer DEFAULT 0 NOT NULL,
	"goals_conceded" integer DEFAULT 0 NOT NULL,
	"saves" integer DEFAULT 0 NOT NULL,
	"penalties_saved" integer DEFAULT 0 NOT NULL,
	"yellow_cards" integer DEFAULT 0 NOT NULL,
	"red_cards" integer DEFAULT 0 NOT NULL,
	"minutes" integer DEFAULT 0 NOT NULL,
	"starts" integer DEFAULT 0 NOT NULL,
	"total_points" integer DEFAULT 0 NOT NULL,
	"bonus" integer DEFAULT 0 NOT NULL,
	"bps" integer DEFAULT 0 NOT NULL,
	"expected_goals" numeric(5, 2),
	"expected_assists" numeric(5, 2),
	"expected_goals_conceded" numeric(5, 2),
	"influence" numeric(5, 1),
	"creativity" numeric(5, 1),
	"threat" numeric(5, 1),
	"ict_index" numeric(5, 1),
	"goals_per_90" numeric(5, 2),
	"assists_per_90" numeric(5, 2),
	"defensive_contribution_per_90" numeric(5, 2),
	"tackles_per_90" numeric(5, 2),
	"recoveries_per_90" numeric(5, 2),
	"cbi_per_90" numeric(5, 2),
	"clean_sheets_per_90" numeric(5, 2),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "player_assist_projections" (
	"player_id" integer NOT NULL,
	"gameweek" integer NOT NULL,
	"season" text DEFAULT '2025/26' NOT NULL,
	"assists" real DEFAULT 0 NOT NULL,
	"calculated_at" timestamp DEFAULT now(),
	CONSTRAINT "player_assist_projections_player_id_gameweek_pk" PRIMARY KEY("player_id","gameweek")
);
--> statement-breakpoint
CREATE TABLE "player_contributions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"player_id" integer NOT NULL,
	"player_name" varchar NOT NULL,
	"team_id" integer NOT NULL,
	"gameweek_range" varchar NOT NULL,
	"season" varchar DEFAULT '2025/26' NOT NULL,
	"projected_goals" numeric(6, 2) DEFAULT '0' NOT NULL,
	"projected_assists" numeric(6, 2) DEFAULT '0' NOT NULL,
	"projected_clean_sheets" numeric(6, 2) DEFAULT '0' NOT NULL,
	"projected_defensive_contributions" numeric(6, 2) DEFAULT '0' NOT NULL,
	"projected_minutes" numeric(6, 2) DEFAULT '0' NOT NULL,
	"projected_bonus" numeric(6, 2) DEFAULT '0' NOT NULL,
	"goals_to_points" numeric(6, 2) DEFAULT '0' NOT NULL,
	"assists_to_points" numeric(6, 2) DEFAULT '0' NOT NULL,
	"clean_sheets_to_points" numeric(6, 2) DEFAULT '0' NOT NULL,
	"defensive_to_points" numeric(6, 2) DEFAULT '0' NOT NULL,
	"minutes_to_points" numeric(6, 2) DEFAULT '0' NOT NULL,
	"bonus_to_points" numeric(6, 2) DEFAULT '0' NOT NULL,
	"goal_share_percentage" numeric(5, 2) DEFAULT '0',
	"assist_share_percentage" numeric(5, 2) DEFAULT '0',
	"last_updated" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "player_defensive_projections" (
	"player_id" integer NOT NULL,
	"gameweek" integer NOT NULL,
	"season" text DEFAULT '2025/26' NOT NULL,
	"defensive_contribution" real DEFAULT 0 NOT NULL,
	"points" real DEFAULT 0 NOT NULL,
	"calculated_at" timestamp DEFAULT now(),
	CONSTRAINT "player_defensive_projections_player_id_gameweek_pk" PRIMARY KEY("player_id","gameweek")
);
--> statement-breakpoint
CREATE TABLE "player_goals_projections" (
	"player_id" integer NOT NULL,
	"gameweek" integer NOT NULL,
	"season" text DEFAULT '2025/26' NOT NULL,
	"goals" real DEFAULT 0 NOT NULL,
	"calculated_at" timestamp DEFAULT now(),
	CONSTRAINT "player_goals_projections_player_id_gameweek_pk" PRIMARY KEY("player_id","gameweek")
);
--> statement-breakpoint
CREATE TABLE "player_mappings" (
	"id" integer PRIMARY KEY NOT NULL,
	"first_name" varchar(100),
	"second_name" varchar(100),
	"web_name" varchar(50),
	"current_team_id" integer NOT NULL,
	"current_team_name" varchar(100),
	"position" varchar(20),
	"last_updated" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "player_minutes_projections" (
	"player_id" integer NOT NULL,
	"gameweek" integer NOT NULL,
	"season" text DEFAULT '2025/26' NOT NULL,
	"minutes" real DEFAULT 0 NOT NULL,
	"calculated_at" timestamp DEFAULT now(),
	CONSTRAINT "player_minutes_projections_player_id_gameweek_pk" PRIMARY KEY("player_id","gameweek")
);
--> statement-breakpoint
CREATE TABLE "player_projections" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"player_id" integer NOT NULL,
	"player_name" varchar NOT NULL,
	"team_id" integer NOT NULL,
	"team_name" varchar NOT NULL,
	"position" varchar NOT NULL,
	"element_type" integer NOT NULL,
	"current_price" integer NOT NULL,
	"ownership" numeric(5, 2) NOT NULL,
	"goal_projections" jsonb NOT NULL,
	"assist_projections" jsonb NOT NULL,
	"clean_sheet_projections" jsonb NOT NULL,
	"minutes_projections" jsonb NOT NULL,
	"defensive_projections" jsonb NOT NULL,
	"total_points_projections" jsonb NOT NULL,
	"total_goals" numeric(5, 2) NOT NULL,
	"total_assists" numeric(5, 2) NOT NULL,
	"total_points" numeric(6, 2) NOT NULL,
	"average_points_per_gameweek" numeric(5, 2) NOT NULL,
	"season_projected_points" integer NOT NULL,
	"gameweek_range" varchar NOT NULL,
	"start_gameweek" integer NOT NULL,
	"end_gameweek" integer NOT NULL,
	"season" varchar DEFAULT '2025/26' NOT NULL,
	"last_updated" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "price_changes" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"player_id" integer NOT NULL,
	"player_name" varchar NOT NULL,
	"team_id" integer,
	"team_name" varchar,
	"position" varchar,
	"old_price" integer NOT NULL,
	"new_price" integer NOT NULL,
	"price_change" integer NOT NULL,
	"change_date" date NOT NULL,
	"ownership" numeric(5, 2) NOT NULL,
	"transfers_in" integer DEFAULT 0,
	"transfers_out" integer DEFAULT 0,
	"transfers_in_gw" integer DEFAULT 0,
	"transfers_out_gw" integer DEFAULT 0,
	"total_season_change" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "projection_update_log" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"update_type" varchar NOT NULL,
	"gameweek_range" varchar NOT NULL,
	"players_updated" integer DEFAULT 0,
	"teams_updated" integer DEFAULT 0,
	"duration" integer NOT NULL,
	"status" varchar NOT NULL,
	"error_details" jsonb,
	"started_at" timestamp NOT NULL,
	"completed_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"sid" varchar PRIMARY KEY NOT NULL,
	"sess" varchar NOT NULL,
	"expire" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "team_clean_sheet_projections" (
	"team_id" integer NOT NULL,
	"gameweek" integer NOT NULL,
	"season" text DEFAULT '2025/26' NOT NULL,
	"clean_sheet_probability" real DEFAULT 0 NOT NULL,
	"calculated_at" timestamp DEFAULT now(),
	CONSTRAINT "team_clean_sheet_projections_team_id_gameweek_pk" PRIMARY KEY("team_id","gameweek")
);
--> statement-breakpoint
CREATE TABLE "team_projections" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"team_id" integer NOT NULL,
	"team_name" varchar NOT NULL,
	"goal_projections" jsonb NOT NULL,
	"clean_sheet_projections" jsonb NOT NULL,
	"goals_against_projections" jsonb NOT NULL,
	"goal_share_data" jsonb NOT NULL,
	"assist_share_data" jsonb NOT NULL,
	"gameweek_range" varchar NOT NULL,
	"start_gameweek" integer NOT NULL,
	"end_gameweek" integer NOT NULL,
	"season" varchar DEFAULT '2025/26' NOT NULL,
	"last_updated" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "unified_projection_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "unified_projection_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"auto_balance" boolean DEFAULT true,
	"league_goals_per_season" integer DEFAULT 1050,
	"global_tier_multiplier" numeric(4, 2) DEFAULT '1.25',
	"low_confidence_boost" numeric(4, 2) DEFAULT '1.25',
	"low_confidence_threshold" numeric(4, 2) DEFAULT '0.65',
	"derby_match_multiplier" numeric(4, 2) DEFAULT '0.87',
	"top_six_match_multiplier" numeric(4, 2) DEFAULT '1.12',
	"relegation_battle_multiplier" numeric(4, 2) DEFAULT '0.83',
	"early_kickoff_multiplier" numeric(4, 2) DEFAULT '0.94',
	"late_kickoff_multiplier" numeric(4, 2) DEFAULT '1.07',
	"post_european_multiplier" numeric(4, 2) DEFAULT '0.88',
	"midweek_fixture_multiplier" numeric(4, 2) DEFAULT '0.91',
	"season_finale_multiplier" numeric(4, 2) DEFAULT '1.05',
	"new_manager_bounce_multiplier" numeric(4, 2) DEFAULT '1.08',
	"weather_conditions_multiplier" numeric(4, 2) DEFAULT '0.96',
	"elite_attack_multiplier" numeric(4, 2) DEFAULT '1.35',
	"strong_attack_multiplier" numeric(4, 2) DEFAULT '1.15',
	"average_attack_multiplier" numeric(4, 2) DEFAULT '1.00',
	"weak_attack_multiplier" numeric(4, 2) DEFAULT '0.85',
	"promoted_attack_multiplier" numeric(4, 2) DEFAULT '0.70',
	"offensive_variance_enabled" boolean DEFAULT false,
	"elite_attacking_goals" integer DEFAULT 80,
	"weak_attacking_goals" integer DEFAULT 35,
	"elite_defense_multiplier" numeric(4, 2) DEFAULT '0.60',
	"strong_defense_multiplier" numeric(4, 2) DEFAULT '0.75',
	"average_defense_multiplier" numeric(4, 2) DEFAULT '1.00',
	"weak_defense_multiplier" numeric(4, 2) DEFAULT '1.35',
	"promoted_defense_multiplier" numeric(4, 2) DEFAULT '1.60',
	"elite_attack_teams" text DEFAULT '[]',
	"strong_attack_teams" text DEFAULT '[]',
	"average_attack_teams" text DEFAULT '[]',
	"weak_attack_teams" text DEFAULT '[]',
	"promoted_attack_teams" text DEFAULT '[]',
	"elite_defense_teams" text DEFAULT '[1]',
	"strong_defense_teams" text DEFAULT '[12,13,7,16,15,9]',
	"average_defense_teams" text DEFAULT '[8,14,18,2,10]',
	"weak_defense_teams" text DEFAULT '[6,19,20,4,5]',
	"promoted_defense_teams" text DEFAULT '[3,11,17]',
	"absolute_min_goals" numeric(4, 2) DEFAULT '0.30',
	"absolute_max_goals" numeric(4, 2) DEFAULT '4.20',
	"market_floor_multiplier" numeric(4, 2) DEFAULT '0.40',
	"market_ceiling_multiplier" numeric(4, 2) DEFAULT '2.00',
	"home_advantage_multiplier" numeric(4, 2) DEFAULT '1.15',
	"away_factor_multiplier" numeric(4, 2) DEFAULT '0.88',
	"last_updated" timestamp DEFAULT now(),
	"updated_by" varchar DEFAULT 'admin'
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar,
	"first_name" varchar,
	"last_name" varchar,
	"profile_image_url" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "historical_players" (
	"id" varchar PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"season" varchar(10) NOT NULL,
	"first_name" varchar(100),
	"second_name" varchar(100),
	"web_name" varchar(50),
	"team_name" varchar(100),
	"team_short_name" varchar(10),
	"position_name" varchar(50),
	"season_name" varchar(10),
	"element_code" integer,
	"start_cost" integer,
	"end_cost" integer,
	"total_points" integer,
	"minutes" integer,
	"goals_scored" integer,
	"assists" integer,
	"clean_sheets" integer,
	"goals_conceded" integer,
	"own_goals" integer,
	"penalties_saved" integer,
	"penalties_missed" integer,
	"yellow_cards" integer,
	"red_cards" integer,
	"saves" integer,
	"bonus" integer,
	"bps" integer,
	"influence" varchar(20),
	"creativity" varchar(20),
	"threat" varchar(20),
	"ict_index" varchar(20),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "price_alerts" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"player_name" text NOT NULL,
	"old_price" integer NOT NULL,
	"new_price" integer NOT NULL,
	"change_type" text NOT NULL,
	"change_amount" integer NOT NULL,
	"alert_triggered" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "watchlist_entries" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"player_name" text NOT NULL,
	"team_name" text NOT NULL,
	"position" text NOT NULL,
	"current_price" integer NOT NULL,
	"target_price" integer,
	"alert_on_rise" boolean DEFAULT false,
	"alert_on_fall" boolean DEFAULT false,
	"notes" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "fpl_creator_tracking" ADD CONSTRAINT "fpl_creator_tracking_creator_id_fpl_content_creators_id_fk" FOREIGN KEY ("creator_id") REFERENCES "public"."fpl_content_creators"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_daily_prices_player_date" ON "daily_player_prices" USING btree ("player_id","record_date");--> statement-breakpoint
CREATE INDEX "idx_daily_prices_date" ON "daily_player_prices" USING btree ("record_date");--> statement-breakpoint
CREATE INDEX "idx_fpl_teams_name" ON "fpl_teams" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_fpl_teams_tier" ON "fpl_teams" USING btree ("attacking_tier");--> statement-breakpoint
CREATE INDEX "idx_gameweek_player_data_player_gw" ON "gameweek_player_data" USING btree ("player_id","gameweek");--> statement-breakpoint
CREATE INDEX "idx_gameweek_player_data_season_gw" ON "gameweek_player_data" USING btree ("season","gameweek");--> statement-breakpoint
CREATE INDEX "idx_historical_player_season" ON "historical_player_stats" USING btree ("player_id","season");--> statement-breakpoint
CREATE INDEX "idx_historical_season" ON "historical_player_stats" USING btree ("season");--> statement-breakpoint
CREATE INDEX "idx_historical_position" ON "historical_player_stats" USING btree ("element_type");--> statement-breakpoint
CREATE INDEX "idx_historical_team" ON "historical_player_stats" USING btree ("team_id");--> statement-breakpoint
CREATE INDEX "idx_historical_player_team_season" ON "historical_player_stats" USING btree ("player_id","team_id","season");--> statement-breakpoint
CREATE INDEX "idx_player_contributions_player" ON "player_contributions" USING btree ("player_id");--> statement-breakpoint
CREATE INDEX "idx_player_contributions_team" ON "player_contributions" USING btree ("team_id");--> statement-breakpoint
CREATE INDEX "idx_player_contributions_range" ON "player_contributions" USING btree ("gameweek_range");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_player_contributions_unique" ON "player_contributions" USING btree ("player_id","gameweek_range","season");--> statement-breakpoint
CREATE INDEX "idx_player_mappings_team" ON "player_mappings" USING btree ("current_team_id");--> statement-breakpoint
CREATE INDEX "idx_player_projections_player" ON "player_projections" USING btree ("player_id");--> statement-breakpoint
CREATE INDEX "idx_player_projections_range" ON "player_projections" USING btree ("start_gameweek","end_gameweek");--> statement-breakpoint
CREATE INDEX "idx_player_projections_total_points" ON "player_projections" USING btree ("total_points");--> statement-breakpoint
CREATE INDEX "idx_player_projections_updated" ON "player_projections" USING btree ("last_updated");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_player_projections_unique" ON "player_projections" USING btree ("player_id","start_gameweek","end_gameweek","season");--> statement-breakpoint
CREATE INDEX "idx_price_changes_player" ON "price_changes" USING btree ("player_id");--> statement-breakpoint
CREATE INDEX "idx_price_changes_date" ON "price_changes" USING btree ("change_date");--> statement-breakpoint
CREATE INDEX "idx_price_changes_player_date" ON "price_changes" USING btree ("player_id","change_date");--> statement-breakpoint
CREATE INDEX "idx_projection_log_type" ON "projection_update_log" USING btree ("update_type");--> statement-breakpoint
CREATE INDEX "idx_projection_log_completed" ON "projection_update_log" USING btree ("completed_at");--> statement-breakpoint
CREATE INDEX "IDX_session_expire" ON "sessions" USING btree ("expire");--> statement-breakpoint
CREATE INDEX "idx_team_projections_team" ON "team_projections" USING btree ("team_id");--> statement-breakpoint
CREATE INDEX "idx_team_projections_range" ON "team_projections" USING btree ("start_gameweek","end_gameweek");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_team_projections_unique" ON "team_projections" USING btree ("team_id","start_gameweek","end_gameweek","season");--> statement-breakpoint
CREATE INDEX "historical_players_season_idx" ON "historical_players" USING btree ("season");--> statement-breakpoint
CREATE INDEX "historical_players_player_season_idx" ON "historical_players" USING btree ("player_id","season");