// Raw transcription of Manual Uploads/xMins/*.jpeg (source: @FPL_SPACEMAN / fpl.solioanalytics.com,
// "BASELINE ALL FIXTURES" projected-lineup probability grids for the 2026/27 season).
// Each row is one (team, position-slot, player, % chance of starting in that slot) entry.
// "New Signing?" placeholder rows (unnamed, no player to match) are omitted.
export interface XMinsRawRow {
  team: string; // matches shared/schema.ts PREMIER_LEAGUE_TEAMS `name`
  position: string;
  player: string;
  pct: number;
}

export const XMINS_RAW_DATA: XMinsRawRow[] = [
  // Chelsea (4-2-3-1)
  { team: "Chelsea", position: "ST", player: "João Pedro", pct: 83 },
  { team: "Chelsea", position: "ST", player: "Welbeck", pct: 15 },
  { team: "Chelsea", position: "ST", player: "Delap", pct: 2 },
  { team: "Chelsea", position: "CAM", player: "Rogers", pct: 58 },
  { team: "Chelsea", position: "CAM", player: "Palmer", pct: 37 },
  { team: "Chelsea", position: "CAM", player: "Enzo", pct: 5 },
  { team: "Chelsea", position: "LW", player: "Neto", pct: 54 },
  { team: "Chelsea", position: "LW", player: "Rogers", pct: 34 },
  { team: "Chelsea", position: "LW", player: "João Pedro", pct: 10 },
  { team: "Chelsea", position: "LW", player: "Quenda", pct: 2 },
  { team: "Chelsea", position: "RW", player: "Palmer", pct: 55 },
  { team: "Chelsea", position: "RW", player: "Estêvão", pct: 30 },
  { team: "Chelsea", position: "RW", player: "Quenda", pct: 9 },
  { team: "Chelsea", position: "RW", player: "Neto", pct: 6 },
  { team: "Chelsea", position: "LDM", player: "Caicedo", pct: 91 },
  { team: "Chelsea", position: "LDM", player: "Barco", pct: 7 },
  { team: "Chelsea", position: "LDM", player: "Lavia", pct: 2 },
  { team: "Chelsea", position: "RDM", player: "Enzo", pct: 75 },
  { team: "Chelsea", position: "RDM", player: "James", pct: 21 },
  { team: "Chelsea", position: "RDM", player: "Henderson", pct: 4 },
  { team: "Chelsea", position: "LB", player: "Hato", pct: 65 },
  { team: "Chelsea", position: "LB", player: "Gusto", pct: 20 },
  { team: "Chelsea", position: "LB", player: "Barco", pct: 11 },
  { team: "Chelsea", position: "LB", player: "Quenda", pct: 4 },
  { team: "Chelsea", position: "RB", player: "James", pct: 72 },
  { team: "Chelsea", position: "RB", player: "Palestra", pct: 25 },
  { team: "Chelsea", position: "RB", player: "Gusto", pct: 3 },
  { team: "Chelsea", position: "LCB", player: "Colwill", pct: 88 },
  { team: "Chelsea", position: "LCB", player: "Hato", pct: 8 },
  { team: "Chelsea", position: "LCB", player: "B.Badiashile", pct: 4 },
  { team: "Chelsea", position: "RCB", player: "Lacroix", pct: 78 },
  { team: "Chelsea", position: "RCB", player: "Fofana", pct: 16 },
  { team: "Chelsea", position: "RCB", player: "Acheampong", pct: 4 },
  { team: "Chelsea", position: "RCB", player: "Tosin", pct: 2 },
  { team: "Chelsea", position: "GK", player: "Sánchez", pct: 98 },
  { team: "Chelsea", position: "GK", player: "Penders", pct: 2 },

  // Liverpool (4-2-3-1)
  { team: "Liverpool", position: "ST", player: "Isak", pct: 68 },
  { team: "Liverpool", position: "ST", player: "Ekitiké", pct: 22 },
  { team: "Liverpool", position: "ST", player: "Gakpo", pct: 9 },
  { team: "Liverpool", position: "ST", player: "Chiesa", pct: 1 },
  { team: "Liverpool", position: "CAM", player: "Wirtz", pct: 90 },
  { team: "Liverpool", position: "CAM", player: "Szoboszlai", pct: 7 },
  { team: "Liverpool", position: "CAM", player: "Mac Allister", pct: 3 },
  { team: "Liverpool", position: "LW", player: "Gakpo", pct: 61 },
  { team: "Liverpool", position: "LW", player: "Muñoz", pct: 18 },
  { team: "Liverpool", position: "LW", player: "Ngumoha", pct: 17 },
  { team: "Liverpool", position: "LW", player: "Wirtz", pct: 4 },
  { team: "Liverpool", position: "RW", player: "Ngumoha", pct: 49 },
  { team: "Liverpool", position: "RW", player: "Szoboszlai", pct: 33 },
  { team: "Liverpool", position: "RW", player: "Frimpong", pct: 13 },
  { team: "Liverpool", position: "RW", player: "Chiesa", pct: 5 },
  { team: "Liverpool", position: "LDM", player: "Szoboszlai", pct: 53 },
  { team: "Liverpool", position: "LDM", player: "Mac Allister", pct: 46 },
  { team: "Liverpool", position: "LDM", player: "Endo", pct: 1 },
  { team: "Liverpool", position: "RDM", player: "Gravenberch", pct: 85 },
  { team: "Liverpool", position: "RDM", player: "C.Jones", pct: 15 },
  { team: "Liverpool", position: "LB", player: "Kerkez", pct: 92 },
  { team: "Liverpool", position: "LB", player: "Tsimikas", pct: 8 },
  { team: "Liverpool", position: "RB", player: "Bradley", pct: 44 },
  { team: "Liverpool", position: "RB", player: "Frimpong", pct: 38 },
  { team: "Liverpool", position: "RB", player: "C.Jones", pct: 10 },
  { team: "Liverpool", position: "RB", player: "Gomez", pct: 8 },
  { team: "Liverpool", position: "LCB", player: "Virgil", pct: 98 },
  { team: "Liverpool", position: "LCB", player: "Endo", pct: 1 },
  { team: "Liverpool", position: "LCB", player: "Leoni", pct: 1 },
  { team: "Liverpool", position: "RCB", player: "Araújo", pct: 80 },
  { team: "Liverpool", position: "RCB", player: "Jacquet", pct: 14 },
  { team: "Liverpool", position: "RCB", player: "Gomez", pct: 5 },
  { team: "Liverpool", position: "RCB", player: "Gravenberch", pct: 1 },
  { team: "Liverpool", position: "GK", player: "A.Becker", pct: 96 },
  { team: "Liverpool", position: "GK", player: "Mamardashvili", pct: 4 },

  // Bournemouth (4-2-3-1)
  { team: "Bournemouth", position: "ST", player: "Evanilson", pct: 72 },
  { team: "Bournemouth", position: "ST", player: "Álvaro Rodriguez", pct: 19 },
  { team: "Bournemouth", position: "ST", player: "Kroupi.Jr", pct: 8 },
  { team: "Bournemouth", position: "ST", player: "Enes Ünal", pct: 1 },
  { team: "Bournemouth", position: "CAM", player: "Kroupi.Jr", pct: 69 },
  { team: "Bournemouth", position: "CAM", player: "Kluivert", pct: 25 },
  { team: "Bournemouth", position: "CAM", player: "Adli", pct: 4 },
  { team: "Bournemouth", position: "CAM", player: "Tavernier", pct: 2 },
  { team: "Bournemouth", position: "LW", player: "Tavernier", pct: 84 },
  { team: "Bournemouth", position: "LW", player: "Kroupi.Jr", pct: 7 },
  { team: "Bournemouth", position: "LW", player: "Brooks", pct: 5 },
  { team: "Bournemouth", position: "LW", player: "Adli", pct: 4 },
  { team: "Bournemouth", position: "RW", player: "Rayan", pct: 86 },
  { team: "Bournemouth", position: "RW", player: "Brooks", pct: 6 },
  { team: "Bournemouth", position: "RW", player: "Adli", pct: 4 },
  { team: "Bournemouth", position: "RW", player: "Tavernier", pct: 4 },
  { team: "Bournemouth", position: "LDM", player: "Scott", pct: 96 },
  { team: "Bournemouth", position: "LDM", player: "Tóth.A", pct: 4 },
  { team: "Bournemouth", position: "RDM", player: "Adams", pct: 79 },
  { team: "Bournemouth", position: "RDM", player: "Cook", pct: 9 },
  { team: "Bournemouth", position: "RDM", player: "Christie", pct: 9 },
  { team: "Bournemouth", position: "RDM", player: "Tavernier", pct: 3 },
  { team: "Bournemouth", position: "LB", player: "Truffert", pct: 98 },
  { team: "Bournemouth", position: "LB", player: "Smith", pct: 2 },
  { team: "Bournemouth", position: "RB", player: "Sanchez", pct: 84 },
  { team: "Bournemouth", position: "RB", player: "Smith", pct: 16 },
  { team: "Bournemouth", position: "LCB", player: "António Silva", pct: 96 },
  { team: "Bournemouth", position: "LCB", player: "Diakité", pct: 4 },
  { team: "Bournemouth", position: "RCB", player: "Hill", pct: 97 },
  { team: "Bournemouth", position: "RCB", player: "Milosavljević", pct: 3 },
  { team: "Bournemouth", position: "GK", player: "Petrović", pct: 99 },
  { team: "Bournemouth", position: "GK", player: "Dennis", pct: 1 },

  // Newcastle (4-2-3-1)
  { team: "Newcastle", position: "ST", player: "Osula", pct: 55 },
  { team: "Newcastle", position: "ST", player: "Wissa", pct: 38 },
  { team: "Newcastle", position: "ST", player: "Woltemade", pct: 7 },
  { team: "Newcastle", position: "CAM", player: "Woltemade", pct: 72 },
  { team: "Newcastle", position: "CAM", player: "Joelinton", pct: 20 },
  { team: "Newcastle", position: "CAM", player: "J.Ramsey", pct: 8 },
  { team: "Newcastle", position: "LW", player: "Barnes", pct: 64 },
  { team: "Newcastle", position: "LW", player: "Bazoumana Touré", pct: 29 },
  { team: "Newcastle", position: "LW", player: "J.Ramsey", pct: 4 },
  { team: "Newcastle", position: "LW", player: "Joelinton", pct: 3 },
  { team: "Newcastle", position: "RW", player: "J.Murphy", pct: 61 },
  { team: "Newcastle", position: "RW", player: "Elanga", pct: 29 },
  { team: "Newcastle", position: "RW", player: "Barnes", pct: 10 },
  { team: "Newcastle", position: "LDM", player: "J.Ramsey", pct: 40 },
  { team: "Newcastle", position: "LDM", player: "L.Miley", pct: 32 },
  { team: "Newcastle", position: "LDM", player: "Joelinton", pct: 28 },
  { team: "Newcastle", position: "RDM", player: "Aladji Bamba", pct: 66 },
  { team: "Newcastle", position: "RDM", player: "Sean Steur", pct: 29 },
  { team: "Newcastle", position: "RDM", player: "Willock", pct: 5 },
  { team: "Newcastle", position: "LB", player: "Hall", pct: 85 },
  { team: "Newcastle", position: "LB", player: "Burn", pct: 13 },
  { team: "Newcastle", position: "LB", player: "Livramento", pct: 2 },
  { team: "Newcastle", position: "RB", player: "Livramento", pct: 90 },
  { team: "Newcastle", position: "RB", player: "L.Miley", pct: 7 },
  { team: "Newcastle", position: "RB", player: "Shahar", pct: 3 },
  { team: "Newcastle", position: "LCB", player: "Botman", pct: 74 },
  { team: "Newcastle", position: "LCB", player: "Burn", pct: 26 },
  { team: "Newcastle", position: "RCB", player: "Thiaw", pct: 94 },
  { team: "Newcastle", position: "RCB", player: "Schär", pct: 6 },
  { team: "Newcastle", position: "GK", player: "Lukás Hornícek", pct: 99 },
  { team: "Newcastle", position: "GK", player: "Jaouen", pct: 1 },

  // Arsenal (4-3-3)
  { team: "Arsenal", position: "LW", player: "Tzolis", pct: 39 },
  { team: "Arsenal", position: "LW", player: "Martinelli", pct: 35 },
  { team: "Arsenal", position: "LW", player: "Eze", pct: 26 },
  { team: "Arsenal", position: "ST", player: "Gyökeres", pct: 50 },
  { team: "Arsenal", position: "ST", player: "Havertz", pct: 46 },
  { team: "Arsenal", position: "ST", player: "G.Jesus", pct: 4 },
  { team: "Arsenal", position: "RW", player: "Saka", pct: 84 },
  { team: "Arsenal", position: "RW", player: "Madueke", pct: 13 },
  { team: "Arsenal", position: "RW", player: "Dowman", pct: 3 },
  { team: "Arsenal", position: "LCM", player: "Rice", pct: 65 },
  { team: "Arsenal", position: "LCM", player: "Eze", pct: 30 },
  { team: "Arsenal", position: "LCM", player: "Lewis-Skelly", pct: 5 },
  { team: "Arsenal", position: "RCM", player: "Ødegaard", pct: 55 },
  { team: "Arsenal", position: "RCM", player: "Bruno G.", pct: 40 },
  { team: "Arsenal", position: "RCM", player: "Merino", pct: 5 },
  { team: "Arsenal", position: "DM", player: "Zubimendi", pct: 44 },
  { team: "Arsenal", position: "DM", player: "Lewis-Skelly", pct: 36 },
  { team: "Arsenal", position: "DM", player: "Bruno G.", pct: 20 },
  { team: "Arsenal", position: "LB", player: "Calafiori", pct: 72 },
  { team: "Arsenal", position: "LB", player: "Hincapie", pct: 28 },
  { team: "Arsenal", position: "RB", player: "J.Timber", pct: 86 },
  { team: "Arsenal", position: "RB", player: "White", pct: 9 },
  { team: "Arsenal", position: "RB", player: "Mosquera", pct: 5 },
  { team: "Arsenal", position: "LCB", player: "Gabriel", pct: 97 },
  { team: "Arsenal", position: "LCB", player: "Hincapie", pct: 3 },
  { team: "Arsenal", position: "RCB", player: "Saliba", pct: 96 },
  { team: "Arsenal", position: "RCB", player: "Mosquera", pct: 4 },
  { team: "Arsenal", position: "GK", player: "Raya", pct: 100 },

  // Aston Villa (4-2-3-1)
  { team: "Aston Villa", position: "ST", player: "Watkins", pct: 87 },
  { team: "Aston Villa", position: "ST", player: "Abraham", pct: 10 },
  { team: "Aston Villa", position: "ST", player: "Guessand", pct: 3 },
  { team: "Aston Villa", position: "CAM", player: "Johan Manzambi", pct: 64 },
  { team: "Aston Villa", position: "CAM", player: "Buendía", pct: 33 },
  { team: "Aston Villa", position: "CAM", player: "Barkley", pct: 3 },
  { team: "Aston Villa", position: "LW", player: "Garnacho", pct: 48 },
  { team: "Aston Villa", position: "LW", player: "Buendía", pct: 48 },
  { team: "Aston Villa", position: "LW", player: "Barkley", pct: 4 },
  { team: "Aston Villa", position: "RW", player: "McGinn", pct: 79 },
  { team: "Aston Villa", position: "RW", player: "Barkley", pct: 8 },
  { team: "Aston Villa", position: "RW", player: "Garnacho", pct: 7 },
  { team: "Aston Villa", position: "RW", player: "Guessand", pct: 6 },
  { team: "Aston Villa", position: "LDM", player: "J.Gomes", pct: 92 },
  { team: "Aston Villa", position: "LDM", player: "Bogarde", pct: 5 },
  { team: "Aston Villa", position: "LDM", player: "Barkley", pct: 3 },
  { team: "Aston Villa", position: "RDM", player: "Kamara", pct: 50 },
  { team: "Aston Villa", position: "RDM", player: "Onana", pct: 37 },
  { team: "Aston Villa", position: "RDM", player: "Lindelöf", pct: 13 },
  { team: "Aston Villa", position: "LB", player: "Maatsen", pct: 55 },
  { team: "Aston Villa", position: "LB", player: "Ruggeri", pct: 40 },
  { team: "Aston Villa", position: "LB", player: "Digne", pct: 5 },
  { team: "Aston Villa", position: "RB", player: "Cash", pct: 88 },
  { team: "Aston Villa", position: "RB", player: "Lindelöf", pct: 10 },
  { team: "Aston Villa", position: "RB", player: "Bogarde", pct: 2 },
  { team: "Aston Villa", position: "LCB", player: "Pau", pct: 59 },
  { team: "Aston Villa", position: "LCB", player: "Mings", pct: 41 },
  { team: "Aston Villa", position: "RCB", player: "Konsa", pct: 90 },
  { team: "Aston Villa", position: "RCB", player: "Lindelöf", pct: 10 },
  { team: "Aston Villa", position: "GK", player: "Martinez", pct: 99 },
  { team: "Aston Villa", position: "GK", player: "M.Bizot", pct: 1 },

  // Brentford (4-2-3-1)
  { team: "Brentford", position: "ST", player: "Thiago", pct: 95 },
  { team: "Brentford", position: "ST", player: "Wilson", pct: 4 },
  { team: "Brentford", position: "ST", player: "Schade", pct: 1 },
  { team: "Brentford", position: "CAM", player: "Damsgaard", pct: 56 },
  { team: "Brentford", position: "CAM", player: "Jensen", pct: 44 },
  { team: "Brentford", position: "LW", player: "Schade", pct: 75 },
  { team: "Brentford", position: "LW", player: "Anthony", pct: 20 },
  { team: "Brentford", position: "LW", player: "Lewis-Potter", pct: 3 },
  { team: "Brentford", position: "LW", player: "O.Dango", pct: 2 },
  { team: "Brentford", position: "RW", player: "O.Dango", pct: 91 },
  { team: "Brentford", position: "RW", player: "Anthony", pct: 7 },
  { team: "Brentford", position: "RW", player: "Jensen", pct: 2 },
  { team: "Brentford", position: "LDM", player: "Yarmoliuk", pct: 95 },
  { team: "Brentford", position: "LDM", player: "Jensen", pct: 5 },
  { team: "Brentford", position: "RDM", player: "Mamadou Sangaré", pct: 82 },
  { team: "Brentford", position: "RDM", player: "Janelt", pct: 18 },
  { team: "Brentford", position: "LB", player: "Lewis-Potter", pct: 48 },
  { team: "Brentford", position: "LB", player: "Henry", pct: 35 },
  { team: "Brentford", position: "LB", player: "Ajer", pct: 14 },
  { team: "Brentford", position: "LB", player: "Hickey", pct: 3 },
  { team: "Brentford", position: "RB", player: "Kayode", pct: 96 },
  { team: "Brentford", position: "RB", player: "Hickey", pct: 2 },
  { team: "Brentford", position: "RB", player: "Ajer", pct: 2 },
  { team: "Brentford", position: "LCB", player: "Collins", pct: 95 },
  { team: "Brentford", position: "LCB", player: "Pinnock", pct: 5 },
  { team: "Brentford", position: "RCB", player: "Van den Berg", pct: 72 },
  { team: "Brentford", position: "RCB", player: "Ajer", pct: 28 },
  { team: "Brentford", position: "GK", player: "Kelleher", pct: 99 },
  { team: "Brentford", position: "GK", player: "Valdimarsson", pct: 1 },

  // Brighton (4-2-3-1)
  { team: "Brighton", position: "ST", player: "Georginio", pct: 54 },
  { team: "Brighton", position: "ST", player: "Kostoulas", pct: 41 },
  { team: "Brighton", position: "ST", player: "Tzimas", pct: 5 },
  { team: "Brighton", position: "CAM", player: "Hinshelwood", pct: 75 },
  { team: "Brighton", position: "CAM", player: "Georginio", pct: 15 },
  { team: "Brighton", position: "CAM", player: "Gomez", pct: 6 },
  { team: "Brighton", position: "CAM", player: "Kostoulas", pct: 4 },
  { team: "Brighton", position: "LW", player: "Minteh", pct: 50 },
  { team: "Brighton", position: "LW", player: "Mitoma", pct: 40 },
  { team: "Brighton", position: "LW", player: "De Cuyper", pct: 8 },
  { team: "Brighton", position: "LW", player: "Zadok Yohanna", pct: 2 },
  { team: "Brighton", position: "RW", player: "Gomez", pct: 66 },
  { team: "Brighton", position: "RW", player: "Minteh", pct: 29 },
  { team: "Brighton", position: "RW", player: "Zadok Yohanna", pct: 5 },
  { team: "Brighton", position: "LDM", player: "Gross", pct: 95 },
  { team: "Brighton", position: "LDM", player: "Hinshelwood", pct: 5 },
  { team: "Brighton", position: "RDM", player: "Baleba", pct: 74 },
  { team: "Brighton", position: "RDM", player: "Ayari", pct: 26 },
  { team: "Brighton", position: "LB", player: "F.Kadıoğlu", pct: 84 },
  { team: "Brighton", position: "LB", player: "De Cuyper", pct: 11 },
  { team: "Brighton", position: "LB", player: "Boscagli", pct: 3 },
  { team: "Brighton", position: "LB", player: "Struijk", pct: 2 },
  { team: "Brighton", position: "RB", player: "Wieffer", pct: 85 },
  { team: "Brighton", position: "RB", player: "Costinha", pct: 11 },
  { team: "Brighton", position: "RB", player: "F.Kadıoğlu", pct: 4 },
  { team: "Brighton", position: "LCB", player: "Struijk", pct: 87 },
  { team: "Brighton", position: "LCB", player: "Dunk", pct: 11 },
  { team: "Brighton", position: "LCB", player: "Boscagli", pct: 2 },
  { team: "Brighton", position: "RCB", player: "Dunk", pct: 63 },
  { team: "Brighton", position: "RCB", player: "Vuskovic", pct: 28 },
  { team: "Brighton", position: "RCB", player: "Michael Svoboda", pct: 9 },
  { team: "Brighton", position: "GK", player: "Verbruggen", pct: 99 },
  { team: "Brighton", position: "GK", player: "Steele", pct: 1 },

  // Coventry City (4-2-3-1)
  { team: "Coventry City", position: "ST", player: "Wright", pct: 72 },
  { team: "Coventry City", position: "ST", player: "Simms", pct: 22 },
  { team: "Coventry City", position: "ST", player: "Thomas-Asante", pct: 6 },
  { team: "Coventry City", position: "CAM", player: "Sakamoto", pct: 70 },
  { team: "Coventry City", position: "CAM", player: "Rudoni", pct: 13 },
  { team: "Coventry City", position: "CAM", player: "Eccles", pct: 10 },
  { team: "Coventry City", position: "CAM", player: "Mason-Clark", pct: 7 },
  { team: "Coventry City", position: "LW", player: "Mason-Clark", pct: 76 },
  { team: "Coventry City", position: "LW", player: "Thomas-Asante", pct: 9 },
  { team: "Coventry City", position: "LW", player: "Eccles", pct: 8 },
  { team: "Coventry City", position: "LW", player: "Tchaouna", pct: 7 },
  { team: "Coventry City", position: "RW", player: "Tchaouna", pct: 62 },
  { team: "Coventry City", position: "RW", player: "Sakamoto", pct: 21 },
  { team: "Coventry City", position: "RW", player: "Rudoni", pct: 9 },
  { team: "Coventry City", position: "RW", player: "Thomas-Asante", pct: 8 },
  { team: "Coventry City", position: "LDM", player: "Grimes", pct: 95 },
  { team: "Coventry City", position: "LDM", player: "Eccles", pct: 5 },
  { team: "Coventry City", position: "RDM", player: "Torp", pct: 83 },
  { team: "Coventry City", position: "RDM", player: "Onyeka", pct: 9 },
  { team: "Coventry City", position: "RDM", player: "Rudoni", pct: 8 },
  { team: "Coventry City", position: "LB", player: "DaSilva", pct: 97 },
  { team: "Coventry City", position: "LB", player: "Bidwell", pct: 3 },
  { team: "Coventry City", position: "RB", player: "Van Ewijk", pct: 96 },
  { team: "Coventry City", position: "RB", player: "Kesler-Hayden", pct: 4 },
  { team: "Coventry City", position: "LCB", player: "Kitching", pct: 88 },
  { team: "Coventry City", position: "LCB", player: "Woolfenden", pct: 12 },
  { team: "Coventry City", position: "RCB", player: "Thomas", pct: 83 },
  { team: "Coventry City", position: "RCB", player: "Aurèle Amenda", pct: 17 },
  { team: "Coventry City", position: "GK", player: "Rushworth", pct: 99 },
  { team: "Coventry City", position: "GK", player: "Wilson", pct: 1 },

  // Crystal Palace (3-4-2-1)
  { team: "Crystal Palace", position: "ST", player: "Mateta", pct: 67 },
  { team: "Crystal Palace", position: "ST", player: "Strand Larsen", pct: 33 },
  { team: "Crystal Palace", position: "LAM", player: "Yeremy", pct: 75 },
  { team: "Crystal Palace", position: "LAM", player: "Johnson", pct: 10 },
  { team: "Crystal Palace", position: "LAM", player: "Kamada", pct: 8 },
  { team: "Crystal Palace", position: "LAM", player: "Nketiah", pct: 7 },
  { team: "Crystal Palace", position: "RAM", player: "Sarr", pct: 95 },
  { team: "Crystal Palace", position: "RAM", player: "Devenny", pct: 1 },
  { team: "Crystal Palace", position: "LWB", player: "Mitchell", pct: 62 },
  { team: "Crystal Palace", position: "LWB", player: "Óscar Mingueza", pct: 38 },
  { team: "Crystal Palace", position: "LCM", player: "Kamada", pct: 45 },
  { team: "Crystal Palace", position: "LCM", player: "Hughes", pct: 45 },
  { team: "Crystal Palace", position: "LCM", player: "Lerma", pct: 10 },
  { team: "Crystal Palace", position: "RCM", player: "Wharton", pct: 96 },
  { team: "Crystal Palace", position: "RCM", player: "Lerma", pct: 4 },
  { team: "Crystal Palace", position: "RWB", player: "Muñoz", pct: 94 },
  { team: "Crystal Palace", position: "RWB", player: "Óscar Mingueza", pct: 6 },
  { team: "Crystal Palace", position: "LCB", player: "Canvot", pct: 90 },
  { team: "Crystal Palace", position: "LCB", player: "Chadi Riad", pct: 10 },
  { team: "Crystal Palace", position: "CB", player: "Richards", pct: 95 },
  { team: "Crystal Palace", position: "CB", player: "Lerma", pct: 5 },
  { team: "Crystal Palace", position: "RCB", player: "Tomiyasu", pct: 90 },
  { team: "Crystal Palace", position: "RCB", player: "Richards", pct: 5 },
  { team: "Crystal Palace", position: "RCB", player: "Canvot", pct: 5 },
  { team: "Crystal Palace", position: "GK", player: "Henderson", pct: 99 },
  { team: "Crystal Palace", position: "GK", player: "Benitez", pct: 1 },

  // Everton (4-2-3-1)
  { team: "Everton", position: "ST", player: "Barry", pct: 71 },
  { team: "Everton", position: "ST", player: "Beto", pct: 29 },
  { team: "Everton", position: "CAM", player: "Dewsbury-Hall", pct: 96 },
  { team: "Everton", position: "CAM", player: "Alcaraz", pct: 2 },
  { team: "Everton", position: "CAM", player: "McNeil", pct: 2 },
  { team: "Everton", position: "LW", player: "Ndiaye", pct: 93 },
  { team: "Everton", position: "LW", player: "George", pct: 5 },
  { team: "Everton", position: "LW", player: "Armstrong", pct: 2 },
  { team: "Everton", position: "RW", player: "Hayden Hackney", pct: 42 },
  { team: "Everton", position: "RW", player: "George", pct: 23 },
  { team: "Everton", position: "RW", player: "Röhl", pct: 21 },
  { team: "Everton", position: "RW", player: "Dibling", pct: 14 },
  { team: "Everton", position: "LDM", player: "Garner", pct: 97 },
  { team: "Everton", position: "LDM", player: "Hayden Hackney", pct: 3 },
  { team: "Everton", position: "RDM", player: "Nørgaard", pct: 87 },
  { team: "Everton", position: "RDM", player: "Iroegbunam", pct: 13 },
  { team: "Everton", position: "LB", player: "Mykolenko", pct: 89 },
  { team: "Everton", position: "LB", player: "Branthwaite", pct: 11 },
  { team: "Everton", position: "RB", player: "O'Brien", pct: 76 },
  // "New Signing? 20%" omitted — no name to match
  { team: "Everton", position: "RB", player: "Patterson", pct: 2 },
  { team: "Everton", position: "RB", player: "Garner", pct: 1 },
  { team: "Everton", position: "RB", player: "Röhl", pct: 1 },
  { team: "Everton", position: "LCB", player: "Branthwaite", pct: 82 },
  { team: "Everton", position: "LCB", player: "Keane", pct: 18 },
  { team: "Everton", position: "RCB", player: "Tarkowski", pct: 85 },
  { team: "Everton", position: "RCB", player: "O'Brien", pct: 15 },
  { team: "Everton", position: "GK", player: "Pickford", pct: 99 },
  { team: "Everton", position: "GK", player: "Travers", pct: 1 },

  // Fulham (4-2-3-1)
  { team: "Fulham", position: "ST", player: "Gonzalo García", pct: 90 },
  { team: "Fulham", position: "ST", player: "Muniz", pct: 9 },
  { team: "Fulham", position: "ST", player: "Kusi-Asare", pct: 1 },
  { team: "Fulham", position: "CAM", player: "King", pct: 45 },
  { team: "Fulham", position: "CAM", player: "Smith Rowe", pct: 38 },
  { team: "Fulham", position: "CAM", player: "César Palacios", pct: 14 },
  { team: "Fulham", position: "CAM", player: "Iwobi", pct: 3 },
  { team: "Fulham", position: "LW", player: "Kevin", pct: 51 },
  { team: "Fulham", position: "LW", player: "Bobb", pct: 27 },
  { team: "Fulham", position: "LW", player: "Iwobi", pct: 13 },
  { team: "Fulham", position: "LW", player: "César Palacios", pct: 9 },
  { team: "Fulham", position: "RW", player: "Bobb", pct: 75 },
  { team: "Fulham", position: "RW", player: "Kevin", pct: 25 },
  { team: "Fulham", position: "LDM", player: "Berge", pct: 95 },
  { team: "Fulham", position: "LDM", player: "Reed", pct: 5 },
  { team: "Fulham", position: "RDM", player: "Iwobi", pct: 87 },
  { team: "Fulham", position: "RDM", player: "Cairney", pct: 13 },
  { team: "Fulham", position: "LB", player: "Robinson", pct: 61 },
  { team: "Fulham", position: "LB", player: "Sessegnon", pct: 39 },
  { team: "Fulham", position: "RB", player: "Tete", pct: 65 },
  { team: "Fulham", position: "RB", player: "Castagne", pct: 35 },
  { team: "Fulham", position: "LCB", player: "Bassey", pct: 78 },
  { team: "Fulham", position: "LCB", player: "J.Cuenca", pct: 22 },
  { team: "Fulham", position: "RCB", player: "Andersen", pct: 80 },
  // "New Signing? 20%" omitted — no name to match
  { team: "Fulham", position: "GK", player: "Leno", pct: 99 },
  { team: "Fulham", position: "GK", player: "Lecomte", pct: 1 },

  // Hull City (4-2-3-1)
  { team: "Hull City", position: "ST", player: "McBurnie", pct: 99 },
  { team: "Hull City", position: "ST", player: "Destan", pct: 1 },
  { team: "Hull City", position: "CAM", player: "Hjertø-Dahl", pct: 70 },
  { team: "Hull City", position: "CAM", player: "Belloumi", pct: 13 },
  { team: "Hull City", position: "CAM", player: "Millar", pct: 9 },
  { team: "Hull City", position: "CAM", player: "Ömür", pct: 8 },
  { team: "Hull City", position: "LW", player: "Millar", pct: 81 },
  { team: "Hull City", position: "LW", player: "Kamara", pct: 11 },
  { team: "Hull City", position: "LW", player: "Dowell", pct: 5 },
  { team: "Hull City", position: "LW", player: "Belloumi", pct: 3 },
  { team: "Hull City", position: "RW", player: "Belloumi", pct: 60 },
  { team: "Hull City", position: "RW", player: "Crooks", pct: 22 },
  { team: "Hull City", position: "RW", player: "David", pct: 13 },
  { team: "Hull City", position: "RW", player: "Kamara", pct: 5 },
  { team: "Hull City", position: "LDM", player: "Slater", pct: 68 },
  { team: "Hull City", position: "LDM", player: "Zambrano", pct: 32 },
  { team: "Hull City", position: "RDM", player: "Crooks", pct: 51 },
  { team: "Hull City", position: "RDM", player: "Hidemasa Morita", pct: 49 },
  { team: "Hull City", position: "LB", player: "Giles", pct: 72 },
  { team: "Hull City", position: "LB", player: "Targett", pct: 26 },
  { team: "Hull City", position: "LB", player: "Jacob", pct: 2 },
  { team: "Hull City", position: "RB", player: "Coyle", pct: 81 },
  { team: "Hull City", position: "RB", player: "Drameh", pct: 19 },
  { team: "Hull City", position: "LCB", player: "Hughes", pct: 73 },
  { team: "Hull City", position: "LCB", player: "Ajayi", pct: 27 },
  { team: "Hull City", position: "RCB", player: "Egan", pct: 92 },
  { team: "Hull City", position: "RCB", player: "McNair", pct: 7 },
  { team: "Hull City", position: "RCB", player: "McCarthy", pct: 1 },
  { team: "Hull City", position: "GK", player: "Konstantinos Tzolakis", pct: 99 },
  { team: "Hull City", position: "GK", player: "Butland", pct: 1 },

  // Ipswich Town (4-2-3-1)
  { team: "Ipswich Town", position: "ST", player: "Daizen Maeda", pct: 47 },
  { team: "Ipswich Town", position: "ST", player: "Emersonn", pct: 37 },
  { team: "Ipswich Town", position: "ST", player: "Hirst", pct: 14 },
  { team: "Ipswich Town", position: "ST", player: "Al-Hamadi", pct: 2 },
  { team: "Ipswich Town", position: "CAM", player: "Núñez", pct: 65 },
  { team: "Ipswich Town", position: "CAM", player: "Mehmeti", pct: 20 },
  { team: "Ipswich Town", position: "CAM", player: "Burns", pct: 9 },
  { team: "Ipswich Town", position: "CAM", player: "Walle Egeli", pct: 6 },
  { team: "Ipswich Town", position: "LW", player: "Jaden", pct: 51 },
  { team: "Ipswich Town", position: "LW", player: "Daizen Maeda", pct: 32 },
  { team: "Ipswich Town", position: "LW", player: "Mehmeti", pct: 13 },
  { team: "Ipswich Town", position: "LW", player: "Szmodics", pct: 4 },
  { team: "Ipswich Town", position: "RW", player: "A.Fatawu", pct: 59 },
  { team: "Ipswich Town", position: "RW", player: "J.Clarke", pct: 27 },
  { team: "Ipswich Town", position: "RW", player: "Burns", pct: 8 },
  { team: "Ipswich Town", position: "RW", player: "Walle Egeli", pct: 6 },
  { team: "Ipswich Town", position: "LDM", player: "Taylor", pct: 63 },
  { team: "Ipswich Town", position: "LDM", player: "Núñez", pct: 27 },
  { team: "Ipswich Town", position: "LDM", player: "Mehmeti", pct: 10 },
  { team: "Ipswich Town", position: "RDM", player: "Florentino", pct: 56 },
  { team: "Ipswich Town", position: "RDM", player: "Matusiwa", pct: 44 },
  { team: "Ipswich Town", position: "LB", player: "Davis", pct: 93 },
  { team: "Ipswich Town", position: "LB", player: "Greaves", pct: 7 },
  { team: "Ipswich Town", position: "RB", player: "Furlong", pct: 88 },
  { team: "Ipswich Town", position: "RB", player: "Johnson", pct: 12 },
  { team: "Ipswich Town", position: "LCB", player: "Diop", pct: 65 },
  { team: "Ipswich Town", position: "LCB", player: "Greaves", pct: 35 },
  { team: "Ipswich Town", position: "RCB", player: "O'Shea", pct: 94 },
  { team: "Ipswich Town", position: "RCB", player: "Kipre", pct: 6 },
  { team: "Ipswich Town", position: "GK", player: "Scherpen", pct: 97 },
  { team: "Ipswich Town", position: "GK", player: "Palmer", pct: 3 },

  // Leeds (3-4-2-1)
  { team: "Leeds", position: "LW", player: "Okafor", pct: 81 },
  { team: "Leeds", position: "LW", player: "Aaronson", pct: 10 },
  { team: "Leeds", position: "LW", player: "Stach", pct: 6 },
  { team: "Leeds", position: "LW", player: "Gnonto", pct: 3 },
  { team: "Leeds", position: "ST", player: "Calvert-Lewin", pct: 95 },
  { team: "Leeds", position: "ST", player: "Nmecha", pct: 4 },
  { team: "Leeds", position: "ST", player: "Okafor", pct: 1 },
  { team: "Leeds", position: "RW", player: "Wilson", pct: 90 },
  { team: "Leeds", position: "RW", player: "Aaronson", pct: 9 },
  { team: "Leeds", position: "RW", player: "James", pct: 1 },
  { team: "Leeds", position: "LWB", player: "Gudmundsson", pct: 83 },
  { team: "Leeds", position: "LWB", player: "Justin", pct: 17 },
  { team: "Leeds", position: "LDM", player: "Stach", pct: 85 },
  { team: "Leeds", position: "LDM", player: "Gruev", pct: 8 },
  { team: "Leeds", position: "LDM", player: "Tanaka", pct: 7 },
  { team: "Leeds", position: "RDM", player: "Ampadu", pct: 95 },
  { team: "Leeds", position: "RDM", player: "Longstaff", pct: 5 },
  { team: "Leeds", position: "RWB", player: "Bogle", pct: 77 },
  { team: "Leeds", position: "RWB", player: "Justin", pct: 17 },
  { team: "Leeds", position: "RWB", player: "James", pct: 6 },
  { team: "Leeds", position: "LCB", player: "Tarik Muharemovic", pct: 94 },
  { team: "Leeds", position: "LCB", player: "Bornauw", pct: 6 },
  { team: "Leeds", position: "CB", player: "Bijol", pct: 85 },
  { team: "Leeds", position: "CB", player: "Rodon", pct: 15 },
  { team: "Leeds", position: "RCB", player: "Rodon", pct: 80 },
  { team: "Leeds", position: "RCB", player: "Justin", pct: 20 },
  { team: "Leeds", position: "GK", player: "Trafford", pct: 99 },
  { team: "Leeds", position: "GK", player: "Perri", pct: 1 },

  // Man City (4-2-3-1)
  { team: "Man City", position: "ST", player: "Haaland", pct: 96 },
  { team: "Man City", position: "ST", player: "Marmoush", pct: 2 },
  { team: "Man City", position: "ST", player: "Semenyo", pct: 2 },
  { team: "Man City", position: "CAM", player: "Cherki", pct: 51 },
  { team: "Man City", position: "CAM", player: "Foden", pct: 45 },
  { team: "Man City", position: "CAM", player: "Semenyo", pct: 4 },
  { team: "Man City", position: "LW", player: "Doku", pct: 77 },
  { team: "Man City", position: "LW", player: "Savinho", pct: 9 },
  { team: "Man City", position: "LW", player: "Marmoush", pct: 8 },
  { team: "Man City", position: "LW", player: "Semenyo", pct: 6 },
  { team: "Man City", position: "RW", player: "Semenyo", pct: 83 },
  { team: "Man City", position: "RW", player: "Foden", pct: 13 },
  { team: "Man City", position: "RW", player: "Savinho", pct: 4 },
  { team: "Man City", position: "LDM", player: "Anderson", pct: 73 },
  { team: "Man City", position: "LDM", player: "O'Reilly", pct: 22 },
  { team: "Man City", position: "LDM", player: "Kovačić", pct: 3 },
  { team: "Man City", position: "LDM", player: "Reijnders", pct: 2 },
  { team: "Man City", position: "RDM", player: "Rodrigo", pct: 81 },
  { team: "Man City", position: "RDM", player: "N.Gonzalez", pct: 19 },
  { team: "Man City", position: "LB", player: "O'Reilly", pct: 61 },
  { team: "Man City", position: "LB", player: "Aït-Nouri", pct: 24 },
  { team: "Man City", position: "LB", player: "Gvardiol", pct: 15 },
  { team: "Man City", position: "RB", player: "Matheus N.", pct: 86 },
  { team: "Man City", position: "RB", player: "Khusanov", pct: 12 },
  { team: "Man City", position: "RB", player: "Lewis", pct: 2 },
  { team: "Man City", position: "LCB", player: "Gvardiol", pct: 74 },
  { team: "Man City", position: "LCB", player: "Rúben", pct: 26 },
  { team: "Man City", position: "RCB", player: "Guéhi", pct: 77 },
  { team: "Man City", position: "RCB", player: "Rúben", pct: 20 },
  { team: "Man City", position: "RCB", player: "Khusanov", pct: 3 },
  { team: "Man City", position: "GK", player: "Donnarumma", pct: 98 },
  { team: "Man City", position: "GK", player: "Rulli", pct: 2 },

  // Man Utd (4-2-3-1)
  { team: "Man Utd", position: "ST", player: "Šeško", pct: 70 },
  { team: "Man Utd", position: "ST", player: "Mbeumo", pct: 24 },
  { team: "Man Utd", position: "ST", player: "Cunha", pct: 5 },
  { team: "Man Utd", position: "ST", player: "Zirkzee", pct: 1 },
  { team: "Man Utd", position: "CAM", player: "B.Fernandes", pct: 98 },
  { team: "Man Utd", position: "CAM", player: "Mount", pct: 1 },
  { team: "Man Utd", position: "CAM", player: "Lacey", pct: 1 },
  { team: "Man Utd", position: "LW", player: "Cunha", pct: 78 },
  { team: "Man Utd", position: "LW", player: "Dorgu", pct: 16 },
  { team: "Man Utd", position: "LW", player: "Amad", pct: 6 },
  { team: "Man Utd", position: "RW", player: "Mbeumo", pct: 60 },
  { team: "Man Utd", position: "RW", player: "Amad", pct: 40 },
  { team: "Man Utd", position: "LDM", player: "Tielemans", pct: 88 },
  { team: "Man Utd", position: "LDM", player: "Mount", pct: 7 },
  { team: "Man Utd", position: "LDM", player: "B.Fernandes", pct: 3 },
  { team: "Man Utd", position: "LDM", player: "Ugarte", pct: 2 },
  { team: "Man Utd", position: "RDM", player: "Andrey Santos", pct: 71 },
  { team: "Man Utd", position: "RDM", player: "Mainoo", pct: 29 },
  { team: "Man Utd", position: "LB", player: "Shaw", pct: 82 },
  { team: "Man Utd", position: "LB", player: "Mazraoui", pct: 10 },
  { team: "Man Utd", position: "LB", player: "Dorgu", pct: 5 },
  { team: "Man Utd", position: "LB", player: "Dalot", pct: 3 },
  { team: "Man Utd", position: "RB", player: "Dalot", pct: 74 },
  { team: "Man Utd", position: "RB", player: "Mazraoui", pct: 16 },
  { team: "Man Utd", position: "RB", player: "Yoro", pct: 10 },
  { team: "Man Utd", position: "LCB", player: "Martinez", pct: 95 },
  { team: "Man Utd", position: "LCB", player: "Heaven", pct: 5 },
  { team: "Man Utd", position: "RCB", player: "Maguire", pct: 51 },
  { team: "Man Utd", position: "RCB", player: "De Ligt", pct: 36 },
  { team: "Man Utd", position: "RCB", player: "Yoro", pct: 13 },
  { team: "Man Utd", position: "GK", player: "Lammens", pct: 99 },
  { team: "Man Utd", position: "GK", player: "Darlow", pct: 1 },

  // Nott'm Forest (3-4-2-1)
  { team: "Nott'm Forest", position: "LW", player: "Hudson-Odoi", pct: 66 },
  { team: "Nott'm Forest", position: "LW", player: "Ndoye", pct: 23 },
  { team: "Nott'm Forest", position: "LW", player: "Bakwa", pct: 8 },
  { team: "Nott'm Forest", position: "LW", player: "Dominguez", pct: 3 },
  { team: "Nott'm Forest", position: "ST", player: "Igor Jesus", pct: 78 },
  { team: "Nott'm Forest", position: "ST", player: "Wood", pct: 21 },
  { team: "Nott'm Forest", position: "ST", player: "Awoniyi", pct: 1 },
  { team: "Nott'm Forest", position: "RW", player: "Gibbs-White", pct: 93 },
  { team: "Nott'm Forest", position: "RW", player: "Hutchinson", pct: 4 },
  { team: "Nott'm Forest", position: "RW", player: "Igor Jesus", pct: 3 },
  { team: "Nott'm Forest", position: "LWB", player: "N.Williams", pct: 96 },
  { team: "Nott'm Forest", position: "LWB", player: "Netz", pct: 2 },
  { team: "Nott'm Forest", position: "LWB", player: "Gibbs-White", pct: 2 },
  { team: "Nott'm Forest", position: "LDM", player: "Xaver Schlager", pct: 72 },
  { team: "Nott'm Forest", position: "LDM", player: "Dominguez", pct: 28 },
  { team: "Nott'm Forest", position: "RDM", player: "Sangaré", pct: 88 },
  { team: "Nott'm Forest", position: "RDM", player: "Yates", pct: 12 },
  { team: "Nott'm Forest", position: "RWB", player: "Aina", pct: 85 },
  { team: "Nott'm Forest", position: "RWB", player: "Savona", pct: 10 },
  { team: "Nott'm Forest", position: "RWB", player: "N.Williams", pct: 5 },
  { team: "Nott'm Forest", position: "LCB", player: "Murillo", pct: 92 },
  { team: "Nott'm Forest", position: "LCB", player: "Morato", pct: 8 },
  { team: "Nott'm Forest", position: "CB", player: "Milenković", pct: 98 },
  { team: "Nott'm Forest", position: "CB", player: "Morato", pct: 2 },
  { team: "Nott'm Forest", position: "RCB", player: "Diomande", pct: 80 },
  { team: "Nott'm Forest", position: "RCB", player: "Jair Cunha", pct: 20 },
  { team: "Nott'm Forest", position: "GK", player: "Sels", pct: 99 },
  { team: "Nott'm Forest", position: "GK", player: "John", pct: 1 },

  // Sunderland (4-2-3-1)
  { team: "Sunderland", position: "ST", player: "Brobbey", pct: 94 },
  { team: "Sunderland", position: "ST", player: "Isidor", pct: 6 },
  { team: "Sunderland", position: "CAM", player: "E.Le Fée", pct: 74 },
  { team: "Sunderland", position: "CAM", player: "Diarra", pct: 22 },
  { team: "Sunderland", position: "CAM", player: "Rigg", pct: 4 },
  { team: "Sunderland", position: "LW", player: "Talbi", pct: 73 },
  { team: "Sunderland", position: "LW", player: "E.Le Fée", pct: 21 },
  { team: "Sunderland", position: "LW", player: "Angulo", pct: 6 },
  { team: "Sunderland", position: "RW", player: "Hume", pct: 57 },
  { team: "Sunderland", position: "RW", player: "Diarra", pct: 17 },
  { team: "Sunderland", position: "RW", player: "Angulo", pct: 14 },
  { team: "Sunderland", position: "RW", player: "Jocelin.T", pct: 12 },
  { team: "Sunderland", position: "LDM", player: "Sadiki", pct: 99 },
  { team: "Sunderland", position: "LDM", player: "Xhaka", pct: 1 },
  { team: "Sunderland", position: "RDM", player: "Xhaka", pct: 94 },
  { team: "Sunderland", position: "RDM", player: "Diarra", pct: 6 },
  { team: "Sunderland", position: "LB", player: "Reinildo", pct: 93 },
  { team: "Sunderland", position: "LB", player: "Hume", pct: 5 },
  { team: "Sunderland", position: "LB", player: "Masuaku", pct: 2 },
  { team: "Sunderland", position: "RB", player: "Mukiele", pct: 79 },
  { team: "Sunderland", position: "RB", player: "Thomas Meunier", pct: 15 },
  { team: "Sunderland", position: "RB", player: "Hume", pct: 6 },
  { team: "Sunderland", position: "LCB", player: "Alderete", pct: 80 },
  { team: "Sunderland", position: "LCB", player: "O'Nien", pct: 10 },
  { team: "Sunderland", position: "LCB", player: "Ballard", pct: 8 },
  { team: "Sunderland", position: "LCB", player: "Hjelde", pct: 2 },
  { team: "Sunderland", position: "RCB", player: "Ballard", pct: 85 },
  { team: "Sunderland", position: "RCB", player: "Mukiele", pct: 11 },
  { team: "Sunderland", position: "RCB", player: "Seelt", pct: 4 },
  { team: "Sunderland", position: "GK", player: "Roefs", pct: 99 },
  { team: "Sunderland", position: "GK", player: "Ellborg", pct: 1 },

  // Spurs (4-2-3-1)
  { team: "Spurs", position: "ST", player: "Solanke", pct: 82 },
  { team: "Spurs", position: "ST", player: "Richarlison", pct: 15 },
  { team: "Spurs", position: "ST", player: "Tel", pct: 3 },
  { team: "Spurs", position: "CAM", player: "Gallagher", pct: 53 },
  { team: "Spurs", position: "CAM", player: "Maddison", pct: 45 },
  { team: "Spurs", position: "CAM", player: "P.M.Sarr", pct: 2 },
  { team: "Spurs", position: "LW", player: "Xavi", pct: 49 },
  { team: "Spurs", position: "LW", player: "Tel", pct: 39 },
  { team: "Spurs", position: "LW", player: "Richarlison", pct: 9 },
  { team: "Spurs", position: "LW", player: "Maddison", pct: 3 },
  { team: "Spurs", position: "RW", player: "Kudus", pct: 61 },
  { team: "Spurs", position: "RW", player: "Kulusevski", pct: 15 },
  { team: "Spurs", position: "RW", player: "Xavi", pct: 14 },
  { team: "Spurs", position: "RW", player: "Odobert", pct: 10 },
  { team: "Spurs", position: "LDM", player: "M.Fernandes", pct: 89 },
  { team: "Spurs", position: "LDM", player: "Bentancur", pct: 8 },
  { team: "Spurs", position: "LDM", player: "Gallagher", pct: 3 },
  { team: "Spurs", position: "RDM", player: "Tonali", pct: 94 },
  { team: "Spurs", position: "RDM", player: "Gray", pct: 5 },
  { team: "Spurs", position: "RDM", player: "Bergvall", pct: 1 },
  { team: "Spurs", position: "LB", player: "Spence", pct: 52 },
  { team: "Spurs", position: "LB", player: "Robertson", pct: 30 },
  { team: "Spurs", position: "LB", player: "Udogie", pct: 13 },
  { team: "Spurs", position: "LB", player: "Van de Ven", pct: 5 },
  { team: "Spurs", position: "RB", player: "Pedro Porro", pct: 95 },
  { team: "Spurs", position: "RB", player: "Spence", pct: 3 },
  { team: "Spurs", position: "RB", player: "Gray", pct: 2 },
  { team: "Spurs", position: "LCB", player: "Van de Ven", pct: 90 },
  { team: "Spurs", position: "LCB", player: "Senesi", pct: 10 },
  { team: "Spurs", position: "RCB", player: "Van Hecke", pct: 95 },
  { team: "Spurs", position: "RCB", player: "Danso", pct: 5 },
  { team: "Spurs", position: "GK", player: "Kinsky", pct: 99 },
  { team: "Spurs", position: "GK", player: "Dúbravka", pct: 1 },
];
